apiVersion: v1
kind: Service
metadata:
  name: nodeone
spec:
  selector:
    app: nodeone
  ports: 
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: nodethree
spec:
  selector:
    app: nodethree
  ports: 
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30002
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: nodetwo
spec:
  selector:
    app: nodetwo
  ports: 
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001
  type: NodePort