apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodethree
  labels:
    app: nodethree
spec:
  selector:
    matchLabels:
      app: nodethree
  template:
    metadata:
      labels:
        app: nodethree
    spec:
      containers:
      - name: nodethree
        image: musicboy0322/distributed-node-three:latest
        command: ["go", "run", "main.go", "/app"]
        ports: 
        - containerPort: 8082

---

apiVersion: v1
kind: Service
metadata:
  name: nodethree
spec:
  selector:
    app: nodethree
  ports: 
    - protocol: TCP
      port: 8082
      targetPort: 8082