apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodetwo
  labels:
    app: nodetwo
spec:
  selector:
    matchLabels:
      app: nodetwo
  template:
    metadata:
      labels:
        app: nodetwo
    spec:
      containers:
      - name: nodetwo
        image: musicboy0322/distributed-node-two:latest
        command: ["go", "run", "main.go", "/app"]
        ports: 
        - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: nodetwo
spec:
  selector:
    app: nodetwo
  ports: 
    - protocol: TCP
      port: 8081
      targetPort: 8081