apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeone
  labels:
    app: nodeone
spec:
  selector:
    matchLabels:
      app: nodeone
  template:
    metadata:
      labels:
        app: nodeone
    spec:
      containers:
      - name: nodeone
        image: musicboy0322/distributed-ledger-node-one:latest
        command: ["go", "run", "main.go", "/app"]
        ports: 
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: nodeone
spec:
  selector:
    app: nodeone
  ports: 
    - protocol: TCP
      port: 8080
      targetPort: 8080